= LeoNet Chatbot
Knogler Simon
1.0.5, 2020-05-07
:sourcedir: ../src/main/java
:icons: font
:toc: left

== 1.Pflichtenheft

=== Ausgangssituation
Die HTL-Leonding ist eine Lehranstalt in Oberösterreich, wo derzeit rund 1000 Schüler unterrichtet werden.

=== Istzustand
Derzeit kann man auf der Website alle nötigen Informationen herraussuchen. Wenn man noch Nähere Informationen braucht,
kann man im Sektretariat anrufen und dort nachfragen.

##### Geschäftsprozesse

1. Navigation auf der Schulwebsite. (z.B "Zeige mir die nächsten anstehenden Termine")
2. Informationen über Lehrer (z.B Sprechstunden), Termine und Informationen der einzelnen Schwerpunkte können über
    Texteingabe abgerufen werden.
3. Leonet soll eine "Persönlichkeit" haben (Gesicht, Humor, ...)

=== Problemstellung
Derzeit muss der User alle Informationen heraussuchen und auf der Website selbst herumnavigieren.
Dies kann manchmal etwas verwirrend sein und viel mehr Zeit in Anspruch nehmen als der User aufbringen möchte.
Informationen, die nicht so oft gesucht werden können auf der Website sehr schlecht gefunden werden.

=== Aufgabenstellung
Es wird ein Chatbot mittels Dialogflow erstellt und in die Website der HTL-Leonding eingebunden. Dieser soll Daten von
Lehrkräften, Termine und generelle Informationen auf der Website mittels Texteingabe suchen und dem User anschaulich
präsentieren. Auch gibt der Bot Fragen oder Themen vor, die der User auswählen kann.

=== Zielsetzung
Der Bot hilft den Benutzern, sich auf der Website besser zurecht zu finden. Die Informationen, die jeder Benutzer braucht können
viel schneller und einfacher gefunden werden. Der Nutzer fühlt sich, sobald er auf der Website ist, mehr willkommen, da LeoNet etwas "menschlichkeit"
bereitstellt. Der User muss nicht den ersten Schritt machen, sondern wird von LeoNet an der Hand geführt, da er direkt angesprochen wird
und von vorgeschlagenen Fragen auswählen kann.


== 2.User-Stories

Wenn ich auf die Website kommne, möchte ich, dass mich der Chatbot mit einer kurzen Nachricht, wie zum Beispiel "Hallo!
ich bin Leonet! Wenn du eine Frage hast, kannst du mir sie gerne Stellen!"

Wenn ich Leonet eine Frage über das Bildungsangebot der Informatik frage, soll sie mir den Link auf dei schon vorhandene
unterseite zu dem Thema vorschlagen.

Wenn Leonet eine Frage nicht verstanden hat oder eine Frage, die nichts mit der HTL-Leonding zu tun hat gefragt wurde,
soll sie nett darauf hinweisen, dass die Frage für sie nicht verständlich ist.

Wenn ich Leonet frage, wie die Telefonnummer des Sekretariats lautet, soll sie mir die richtige Telefonnummer Vorschlagen
und dabei eine nette und etwas lustigere Nachricht, wie zum Beispiel "Probiere diese Nummer einmal, die hat bis jetzt immer"
funktioniert", anhängen.


== 3. Anwendungsbeispiele
Der User wählt den vorgeschlagenen Punkt "Erfahre etwas über unser Bildungsangebot" aus und gelangt so auf die Unterseite "https://www.htl-leonding.ac.at/bildungsangebot".

Der User gibt in das Eingabefeld "Informatik" ein. Darauf antwortet der Chatbot mit "Ich habe viele Informationen über die Informatik hier gefunden: https://www.htl-leonding.ac.at/billdungsangebot/informatik"

Der User interagiert nicht mit dem Chatbot, deswegen wird das Fenster klein und bleibt in der linken unteren Ecke des Bildschirms.

Der User findet keine Informationen über das Schulradio und gibt darauf hin in das Eingabefenster "Wo finde ich das Schulradio?" ein. LeoNet antwortet darauf "Infos über das Schulradio findest du unter https://www.htl-leonding.ac.at/aktivitaeten/schulradio ". Der User klickt auf den Link und gelangt so auf die entsprechende Unterseite.

Ein Schüler muss einem Professor eine eMail schicken, doch findet die richtige Adresse nicht. Deswegen gibt er im Eingabefenster den namen des Professors ein. LeoNet gibt daraufhin zurück "Ich habe alle Informationen die du brauchen könntest hier gefunden: https://www.htl-leonding.ac.at/kontakt/lehrer-innen/". Auf dieser Unterseite wurde schon nach dem Professor gesucht, dass der Schüler direkt die Informationen findet.


== 4. Produktvergleich
Magenta - Tinka https://www.magenta.at/

Linz - Elli https://www.linz.at/db/chatbot/

Drei - Troy https://www.drei.at/de/privat/

Heek - Chatbot für das Designen von Websites https://www.heek.com/app/editor

Cubertbyusphones - Cubert https://cubertbuysphones.com/cubert/

An artful science - Milo https://anartfulscience.com/milo.php

Pandora Bots - Mitsuku https://www.pandorabots.com/mitsuku/