= Leonet Chatbot
Simon Knogler, FLorian Klausner
1.0.1, 2020-03-21
:sourcedir: ../src/main/java
:icons: font
:toc: left


== 1.Pflichtenheft


=== Ausgangssituation
Die HTL-Leonding ist eine Lehranstalt in Oberösterreich, wo derzeit rund 1000 Schüler unterrichtet werden.

=== Istzustand
Derzeit kann man auf der Website alle nötigen Informationen herraussuchen. Wenn man noch Nähere Informationen braucht,
kann man im Sektretariat anrufen und dort nachfragen.

##### Geschäftsprozesse

1. Navigation auf der Schulwebsite. (z.B "Zeige mir die nächsten anstehenden Termine")
2. Informationen über Lehrer (z.B Sprechstunden), Termine und Informationen der einzelnen Schwerpunkte können über
    Texteingabe abgerufen werden.
3. Leonet soll eine "Persönlichkeit" haben (Gesicht, Humor, ...)

=== Problemstellung
Derzeit muss der User alle Informationen heraussuchen und auf der Website selbst herumnavigieren.
Dies kann manchmal etwas verwirrend sein und viel mehr Zeit in Anspruch nehmen als der User aufbringen möchte.
Informationen, die nicht so oft gesucht werden können auf der Website sehr schlecht gefunden werden.

=== Aufgabenstellung
Es wird ein Chatbot mittels Dialogflow erstell und in die Website der HTL-Leonding eingebunden. Dieser soll Daten von
Lehrkräften, Termine und generelle Informationen auf der Website mittels Texteingabe suchen und dem User anschaulich
präsentieren.

=== Zielsetzung
Es wird ein Chatbot mittels Dialogflow erstell und in die Website der HTL-Leonding eingebunden. Dieser soll Daten von
Lehrkräften, Termine und generelle Informationen auf der Website mittels Texteingabe suchen und dem User anschaulich
präsentieren.

== 2.User-Stories


